site_name: DesignSafe User Guide
site_description: DesignSafe User Guide
site_url: https://designsafe-ci.org/user-guide/

nav:
  - Home: index.md
  - Cloud Storage Data Transfer: cloudstoragetransfer.md
  - Command-Line Data Transfer: commandlinetransfer.md
  - Cyberduck Data Transfer: cyberducktransfer.md
  - Data Depot: datadepot.md
  - Data Depot Browser: datadepotbrowser.md
  - Data Management Plan Guidance: datamanagementplan.md
  - Data Transfer Guide: datatransfer.md
  - Experimental Facility Checklist: experimentalfacilitychecklist.md
  - Globus Data Transfer: globusdatatransfer.md
  - Jupyter Browser: jupyterbrowser.md

theme: readthedocs

plugins:
  - search
