site_name: DesignSafe User Guide
site_description: DesignSafe User Guide
site_url: https://designsafe-ci.org/user-guide/
plugins:
  - search

theme: 
    name: readthedocs
    highlightjs: true
    features:
      - navigation.top

markdown_extensions:
  - footnotes
  - def_list
  - admonition
  - attr_list
  - abbr

nav:
  - Managing Files: 
    - Data Depot: managingdata/datadepot.md
#   - Globus Command Line: managingdata/globuscommandlinetransfer.md
    - Setting Path to DS on Corral: managingdata/settingpathtodesignsafe.md
#   - Cloud Storage Data Transfer: managingdata/cloudstoragetransfer.md
#   - Command-Line Data Transfer: managingdata/commandlinetransfer.md
#   - Cyberduck Data Transfer: managingdata/cyberducktransfer.md
#   - Data Depot Browser: managingdata/datadepotbrowser.md
#   - Globus Data Transfer: managingdata/globusdatatransfer.md
#   - Jupyter Browser: managingdata/jupyterbrowser.md
    - Data Transfer Guides: managingdata/datatransfer.md
    - Data Management Plan Guidance: managingdata/datamanagementplan.md
    - Experimental Facility Checklist: managingdata/experimentalfacilitychecklist.md

  - Curating &amp; Publishing Projects:
    - Curation &amp; Publication Guides: curating/guides.md
    - Best Practices: curating/bestpractices.md
    - Data Depot/Curation Office Hours: curating/officehours.md
    - Metrics Documentation: curating/metrics.md
    - Curation &amp; Publication FAQ: curating/faq.md
    - Policies: curating/policies.md

  - Analysis Applications: 
     - Overview: analysis/analysis-overview.md
     - HVSRweb: analysis/analysis-hvsrweb.md
     - Jupyter: analysis/analysis-jupyter.md
     - MATLAB: analysis/analysis-matlab.md
     - SWbatch: analysis/analysis-swbatch.md

  - Simulation Applications: 
    - Overview: tools/simulation/overview.md
    - ADCIRC: tools/simulation/adcirc.md
    - Clawpack: tools/simulation/clawpack.md
    - Dakota: tools/simulation/dakota.md
    - LS-DYNA: tools/simulation/lsdyna.md
    - OpenFOAM: tools/simulation/openfoam.md
    - OpenSEES: tools/simulation/opensees.md

  - Visualization Applications: 
    - Overview: tools/visualization/overview.md
    - FigureGen: tools/visualization/figuregen.md
    - Hazmapper: tools/visualization/hazmapper.md
    - Kalpana: tools/visualization/kalpana.md
    - Paraview: tools/visualization/paraview.md
    - Potree Converter: tools/visualization/potree-converter.md
    - Potree Viewer: tools/visualization/potree-viewer.md
    - QGIS: tools/visualization/qgis.md
    - STKO: tools/visualization/stko.md
    - VisIt: tools/visualization/visit.md

  - Hazard Applications: tools/hazard.md
  - Utilities: tools/utilities.md
  - Jupyter Hub: tools/jupyterhub.md
  - Recon Portal Guide: tools/recon/recon.md

  - Advanced:
    - API Developer's Guide: https://tapis-cli.readthedocs.io/en/latest/
    - HPC Allocations Policy: tools/advanced/hpcallocations.md
    - Cybersecurity Policy: tools/advanced/cybersecurity.md
    - DesignSafe FAQ: tools/advanced/dsfaq.md



