site_name: DesignSafe User Guide
site_description: DesignSafe User Guide
site_url: https://designsafe-ci.org/user-guide/
plugins:
  - search
  - include-markdown

theme:
    name: readthedocs
    navigation_depth: 3
    collapse_navigation: false
    custom_dir: themes/ds-readthedocs
    highlightjs: true
    features:
      - navigation.top
    ds_navigation_redirects:
      - before: '#data-depotcuration-office-hours'
        after: https://www.designsafe-ci.org/facilities/virtual-office-hours/

extra_css:
    - css/ds-docs.css

extra_javascript:
    - js/changeNavMarkup.js
    # some JavaScript is included as modules in `./themes/ds-readthedocs/`

markdown_extensions:
  - footnotes
  - def_list
  - admonition
  - attr_list
  - abbr
  - toc:
      permalink: True

nav:
  - Data Depot:
    - Managing Data: managingdata.md
    - Curating &amp; Publishing Projects: curating.md
      # NOTE: External link is achieved via `js/changeNavMarkup.js`, NOT here
      # - Data Depot/Curation Office Hours: https://www.designsafe-ci.org/facilities/virtual-office-hours/
    - Recon Portal: recon.md

  - Tools and Apps:
    - Jupyter Hub: tools/jupyterhub.md
    - Simulation Applications: tools/simulation.md
    - Visualization Applications: tools/visualization.md
    - Analysis Applications: analysis.md
    - Hazard Apps & Utilities: tools/hazard_utils.md

  - Advanced:
    - API Developer's Guide: https://tapis-cli.readthedocs.io/en/latest/
    - HPC Allocations Policy: tools/advanced/hpcallocations.md
    - Cybersecurity Policy: tools/advanced/cybersecurity.md
    - DesignSafe FAQ: tools/advanced/dsfaq.md

  - Use Cases:
    # NOTE: These documents are disabled until a certain one does not freeze build
    # - Use Cases Products: usecases.md
    - Use Cases Products: https://www.designsafe-ci.org/rw/use-cases/
