INHERIT: ./mkdocs.base.yml

site_name: DesignSafe User Guide
site_description: DesignSafe User Guide
site_url: https://designsafe-ci.org/user-guide/
# NOTE: Unrecognized by MkDocs, but recognized by ReadTheDocs theme
site_favicon: https://www.designsafe-ci.org/favicon.ico

theme:
    name: readthedocs
    logo: https://www.designsafe-ci.org/static/images/org_logos/Horizontal-DS.b190a072b800.jpg
    cms_url: https://designsafe-ci.org/ # TACC Feature
    cms_name: designsafe-ci.org # TACC Feature
    navigation_depth: 2
    collapse_navigation: false
    highlightjs: true
    features:
      - navigation.top

extra_css:
  # TACC/TACC-Docs:/mkdocs.base.yml
  - css/core/bootstrap.css
  - css/core/core-styles.css
  - css/core/tacc-docs.css
  # DesignSafe/DS-User-Guide
  - css/ds-docs.css

extra_javascript:
  # TACC/TACC-Docs:/mkdocs.base.yml
  - js/autoScrollNav.js
  - js/addPageId.js
  # DesignSafe/DS-User-Guide
  - js/changeNavMarkup.js

markdown_extensions:
  # TACC/TACC-Docs:/mkdocs.base.yml
  - footnotes
  - def_list
  - admonition
  - attr_list
  - abbr
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.saneheaders
  - pymdownx.details
  - pymdownx.blocks.tab
  - pymdownx.blocks.html
  # DesignSafe/DS-User-Guide
  - pymdownx.snippets:
      base_path: docs

plugins:
  - search
  - exclude-search:
      exclude:
        - aliases.md
        - include/*
        - index-sample/*
        - code-examples/*
        - testingextensions.md
        - archives/*
  - macros

nav:
  - Data Depot:
    - Managing Data: managingdata.md
    - Curating &amp; Publishing Projects: curating.md
    - Recon Portal: recon.md

  - Tools and Apps:
    - Jupyter Hub: tools/jupyterhub.md
    - Simulation Applications: tools/simulation.md
    - Visualization Applications: tools/visualization.md
    - Analysis Applications: analysis.md
    - Hazard Apps & Utilities: tools/hazard_utils.md

  - Advanced:
    - API Developer's Guide: https://tapis-cli.readthedocs.io/en/latest/
    - HPC Allocations Policy: tools/advanced/hpcallocations.md
    - Cybersecurity Policy: tools/advanced/cybersecurity.md
    - DesignSafe FAQ: tools/advanced/dsfaq.md

  - Use Cases:
    - Use Cases Products: usecases.md
