site_name: DesignSafe User Guide
site_description: DesignSafe User Guide
site_url: https://designsafe-ci.org/user-guide/
plugins:
  - search
  - include-markdown

theme:
    name: readthedocs
    navigation_depth: 2
    collapse_navigation: false
    highlightjs: true
    features:
      - navigation.top

extra_css:
    - css/ds-docs.css

extra_javascript:
    - js/changeNavMarkup.js

markdown_extensions:
  - footnotes
  - def_list
  - admonition
  - attr_list
  - abbr

nav:
  - Data Depot:
    - Managing Data: managingdata.md
    - Curating &amp; Publishing Projects: curating.md
    - Recon Portal: recon.md

  - Tools and Apps:
    - Jupyter Hub: tools/jupyterhub.md
    - Simulation Applications: tools/simulation.md
    - Visualization Applications: tools/visualization.md
    - Analysis Applications: analysis.md
    - Hazard Apps & Utilities: tools/hazard_utils.md

  - Advanced:
    - API Developer's Guide: https://tapis-cli.readthedocs.io/en/latest/
    - HPC Allocations Policy: tools/advanced/hpcallocations.md
    - Cybersecurity Policy: tools/advanced/cybersecurity.md
    - DesignSafe FAQ: tools/advanced/dsfaq.md

  - Use Cases:
    - Use Cases Products: usecases.md
