site_name: DesignSafe User Guide
site_description: DesignSafe User Guide
site_url: https://designsafe-ci.org/user-guide/
theme: readthedocs
plugins:
  - search

markdown_extensions:
  - footnotes
  - def_list
  - admonition
  - attr_list
  - abbr

nav:
  - Tools &amp; Applications:
    - Applications:
      - Analysis: 
        - Overview: tools/applications/analysis/analysis-overview.md
        - HVSRweb: tools/applications/analysis/analysis-hvsrweb.md
        - Jupyter: tools/applications/analysis/analysis-jupyter.md
        - MATLAB: tools/applications/analysis/analysis-matlab.md
        - SWbatch: tools/applications/analysis/analysis-swbatch.md
      - Simulation: 
        - Overview: tools/applications/simulation/overview.md
        - ADCIRC: tools/applications/simulation/adcirc.md
        - Clawpack: tools/applications/simulation/clawpack.md
        - Dakota: tools/applications/simulation/dakota.md
        - LS-DYNA: tools/applications/simulation/lsdyna.md
        - OpenFOAM: tools/applications/simulation/openfoam.md
        - OpenSEES: tools/applications/simulation/opensees.md
      - Visualization: tools/applications/visualization
      - Hazard Apps: tools/applications/hazard
      - Utilities: tools/applications/utilities.md
    - Recon Portal Guide: tools/recon.md
    - Jupyter Guide: tools/jupyter.md
    - Advanced:
      - API Developer's Guide: tools/advanced/apideveloperguide.md
      - HPC Allocations Policy: tools/advanced/apideveloperguide.md
      - Cybersecurity Policy: tools/advanced/apideveloperguide.md
      - DesignSafe FAQ: tools/advanced/apideveloperguide.md
  - Managing Files: 
    - Data Depot: managingdata/datadepot.md
    - Data Transfer Guide: managingdata/datatransfer.md
    - Data Management Plan Guidance: managingdata/datamanagementplan.md
    - Experimental Facility Checklist: managingdata/experimentalfacilitychecklist.md
  - Curating &amp; Publishing Projects:
    - Curation &amp; Publication Guides: curating/guides.md
    - Best Practices: curating/bestpractices.md
    - Data Depot/Curation Office Hours: curating/officehours.md
    - Metrics Documentation: curating/metrics.md
    - Curation &amp; Publication FAQ: curating/faq.md
    - Policies: curating/policies.md

# Managing Data files hidden to emulate original DS design
#  - Globus Command Line: globuscommandlinetransfer.md
#  - Setting Path to DS on Corral: settingpathtodesignsafe.md
#  - Cloud Storage Data Transfer: cloudstoragetransfer.md
#  - Command-Line Data Transfer: commandlinetransfer.md
#  - Cyberduck Data Transfer: cyberducktransfer.md
#  - Data Depot Browser: datadepotbrowser.md
#  - Globus Data Transfer: globusdatatransfer.md
#  - Jupyter Browser: jupyterbrowser.md


