site_name: DesignSafe User Guide
site_description: DesignSafe User Guide
site_url: https://designsafe-ci.org/user-guide/
plugins:
  - search

theme: 
    name: readthedocs
    highlightjs: true
    features:
      - navigation.top

markdown_extensions:
  - footnotes
  - def_list
  - admonition
  - attr_list
  - abbr

nav:
  - Tools &amp; Applications :
    - Applications:
      - Analysis: 
        - Overview: tools/applications/analysis/analysis-overview.md
        - HVSRweb: tools/applications/analysis/analysis-hvsrweb.md
        - Jupyter: tools/applications/analysis/analysis-jupyter.md
        - MATLAB: tools/applications/analysis/analysis-matlab.md
        - SWbatch: tools/applications/analysis/analysis-swbatch.md
      - Simulation : 
        - Overview: tools/applications/simulation/overview.md
        - ADCIRC: tools/applications/simulation/adcirc.md
        - Clawpack: tools/applications/simulation/clawpack.md
        - Dakota: tools/applications/simulation/dakota.md
        - LS-DYNA: tools/applications/simulation/lsdyna.md
        - OpenFOAM: tools/applications/simulation/openfoam.md
        - OpenSEES: tools/applications/simulation/opensees.md
      - Visualization: 
        - Overview: tools/applications/visualization/overview.md
        - FigureGen: tools/applications/visualization/figuregen.md
        - Hazmapper: tools/applications/visualization/hazmapper.md
        - Kalpana: tools/applications/visualization/kalpana.md
        - Paraview: tools/applications/visualization/paraview.md
        - Potree Converter: tools/applications/visualization/potree-converter.md
        - Potree Viewer: tools/applications/visualization/potree-viewer.md
        - QGIS: tools/applications/visualization/qgis.md
        - STKO: tools/applications/visualization/stko.md
        - VisIt: tools/applications/visualization/visit.md
      - Hazard Apps: tools/applications/hazard.md
      - Utilities: tools/applications/utilities.md
    - Jupyter Hub:
      - Basic Info: tools/jupyter/basicinfo.md
      - Example Notebooks: tools/jupyter/examplenotebooks.md
      - Publishing Notebooks: tools/jupyter/publishingnotebooks.md
    - Recon Portal Guide: tools/recon/recon.md
    - Advanced:
      - API Developer's Guide: https://tapis-cli.readthedocs.io/en/latest/
      - HPC Allocations Policy: tools/advanced/hpcallocations.md
      - Cybersecurity Policy: tools/advanced/cybersecurity.md
      - DesignSafe FAQ: tools/advanced/dsfaq.md
  - Data Depot:
    - Managing Files: 
      - Data Depot: managingdata/datadepot.md
      - Data Transfer Guide: managingdata/datatransfer.md
      - Data Management Plan Guidance: managingdata/datamanagementplan.md
      - Experimental Facility Checklist: managingdata/experimentalfacilitychecklist.md
    - Curating &amp; Publishing Projects:
      - Curation &amp; Publication Guides: curating/guides.md
      - Best Practices: curating/bestpractices.md
      - Data Depot/Curation Office Hours: curating/officehours.md
      - Metrics Documentation: curating/metrics.md
      - Curation &amp; Publication FAQ: curating/faq.md
      - Policies: curating/policies.md

# Managing Data files hidden to emulate original DS design
#  - Globus Command Line: globuscommandlinetransfer.md
#  - Setting Path to DS on Corral: settingpathtodesignsafe.md
#  - Cloud Storage Data Transfer: cloudstoragetransfer.md
#  - Command-Line Data Transfer: commandlinetransfer.md
#  - Cyberduck Data Transfer: cyberducktransfer.md
#  - Data Depot Browser: datadepotbrowser.md
#  - Globus Data Transfer: globusdatatransfer.md
#  - Jupyter Browser: jupyterbrowser.md


