site_name: DesignSafe User Guide
site_description: DesignSafe User Guide
site_url: https://designsafe-ci.org/user-guide/

nav:
  - Home: index.md
  - Data Depot: datadepot.md

theme: readthedocs

plugins:
  - search
