site_name: DesignSafe User Guide
site_description: DesignSafe User Guide
site_url: https://designsafe-ci.org/user-guide/

nav:
  - Home: index.md
  - Managing Files: 
    - Data Depot: datadepot.md
    - Data Transfer Guide: datatransfer.md
    - Data Management Plan Guidance: datamanagementplan.md
    - Experimental Facility Checklist: experimentalfacilitychecklist.md
# hidden to emulate original DS design
#  - Globus Command Line: globuscommandlinetransfer.md
#  - Setting Path to DS on Corral: settingpathtodesignsafe.md
#  - Cloud Storage Data Transfer: cloudstoragetransfer.md
#  - Command-Line Data Transfer: commandlinetransfer.md
#  - Cyberduck Data Transfer: cyberducktransfer.md
#  - Data Depot Browser: datadepotbrowser.md
#  - Globus Data Transfer: globusdatatransfer.md
#  - Jupyter Browser: jupyterbrowser.md

  - Curating &amp; Publishing Projects:
    - FAQ: curating/faq.md
#   - Curation & Publication Guide
#   - Best Practices:
#   - Data Depot/Curation Office Hours:
#   - Metrics Documentation:
#   - Curation & Publication FAQ:
#   - Policies:
#     - Mission &amp; History: curating/policies/history.md
#     - Governance: curating/policies/governance.md
#     - Data Collections Development: curating/policies/governance.md
#     - Data Curation: curating/policies/governance.md
#     - Data Publication: curating/policies/governance.md
#     - Data Preservation: curating/policies/governance.md

theme: readthedocs

plugins:
  - search
