SRC =   \
	overview.md \
	haan/usecase.md \
	vantassel_and_zhang/usecase.md \
	brandenberg/usecase.md \
	kumar/usecase.md \
	dawson/usecase.md \
	dawson/usecase2.md \
	padgett/usecase.md \
	kareem/usecase.md \
	pinelli/usecase.md \
	arduino/usecase.md \
	lowes/usecase.md  \
	rathje/usecase.md \
	mosqueda/usecase.md \
	brandenberg/apiusecases/usecase.md


usecases:	$(SRC) 
	cat $(SRC) > usecases.md
	/bin/mv usecases.md ..
